# Generated by Django 4.0.6 on 2022-08-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_banner_cta_homepage_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_sitename',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
