# Generated by Django 4.0.6 on 2022-08-20 21:35

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('minifigs', '0002_minifigcarouselimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='minifigsdetailpage',
            name='minifig_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Additional comments that may appear on the detail page.', null=True),
        ),
    ]
