# Generated by Django 4.0.6 on 2022-08-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_globalsitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsitesettings',
            name='site_subtitle',
            field=models.CharField(blank=True, help_text='A subtitle or Slogan you would like to appear under the sitename in some cases', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='globalsitesettings',
            name='websitename',
            field=models.CharField(help_text='The Website name (Title)', max_length=30, null=True),
        ),
    ]
