# Generated by Django 4.0.6 on 2022-08-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(help_text='Email Address', max_length=100)),
                ('full_name', models.CharField(help_text='First and Last name', max_length=100)),
            ],
        ),
    ]
