# Generated by Django 4.0.6 on 2022-08-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetsListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('set_id', models.CharField(help_text='The Set or Box ID of the given set.', max_length=10)),
                ('set_name', models.CharField(help_text='The set name', max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SetsDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('set_id', models.CharField(help_text='The Set or Box ID of the given set.', max_length=10)),
                ('set_name', models.CharField(help_text='The set name', max_length=150)),
                ('set_pieces', models.IntegerField(blank=True, help_text='The piece count of this set.', null=True)),
                ('set_image', models.ForeignKey(blank=True, help_text='The main image of this set i.e. the one you want displayed as Thumbnails, in searches etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
