# Generated by Django 4.0.6 on 2022-08-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0002_remove_setslistingpage_set_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setsdetailpage',
            name='set_name',
        ),
    ]
